---
title: "sentiments_rmd"
author: "Adarsh"
date: "30/07/2021"
output:
  word_document: default
  html_document: default
---


```{r}

library(tidytext)
get_sentiments("bing")
library("janeaustenr")
library("stringr")
library("dplyr")
library("RMySQL")
```
```{r}
sentiments_data <- austen_books() %>%
  group_by(book) %>%
  mutate(linenumber = row_number(),
         chapter = cumsum(str_detect(text, regex("^chapter [\\divxlc]",ignore_case = TRUE)))) %>%
  ungroup( ) %>%
  unnest_tokens(word, text)
```


```{r}
positive_senti <- get_sentiments("bing") %>%
  filter(sentiment == "positive")
negative_senti<- get_sentiments("bing") %>%
  filter(sentiment == "negative")
```

```{r}
sentiments_data %>%
  filter(book == "Emma") %>%
  semi_join(positive_senti) %>%
  count(word, sort = TRUE)
```

```{r}
sentiments_data %>%
  filter(book == "Pride & Prejudice") %>%
  semi_join(negative_senti) %>%
  count(word, sort = TRUE)
```

```{r}

library("tidyr")
bing <- get_sentiments("bing")
Emma_sentiment <- sentiments_data %>%
  inner_join(bing) %>%
  count(book = "Emma" , index = linenumber %/% 80, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative)
```

```{r}
bing <- get_sentiments("bing")
Pride_sentiment <- sentiments_data %>%
  inner_join(bing) %>%
  count(book = "Pride & Prejudice" , index = linenumber %/% 80, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative)
```

```{r}

library(ggplot2)
ggplot(Emma_sentiment, aes(index, sentiment, fill = book)) +
  geom_bar(stat = "identity", show.legend = TRUE) +
  facet_wrap(~book, ncol = 2, scales = "free_x")

ggplot(Pride_sentiment, aes(index, sentiment, fill = book)) +
  geom_bar(stat = "identity", show.legend = TRUE) +
  facet_wrap(~book, ncol = 2, scales = "free_x")
```

```{r}
counting_words <- sentiments_data %>%
  inner_join(bing) %>%
  count(word, sentiment, sort = TRUE)
head(counting_words)
```

```{r}
counting_words %>%
  filter(n > 150) %>%
  mutate(n = ifelse(sentiment == "negative", -n, n)) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sentiment))+
  geom_col() +
  coord_flip() +
  labs(y = "Sentiment Score")
```

